### PR TITLE
charadata data dumped to a backup file

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
NOTE: The table and column names are being discussed and will be changing.

PR is in reference to: https://internal.cida.usgs.gov/jira/browse/WATERSMART-631

I created this file with: $ pg_dump -h localhost -p 5432 -U nldi -W -a -d nldi -n charadata -f charadata_yahara.backup -F tar 

Where -a is for data-only, -d is database, -n is schema. -W is password, otherwise I think the inputs are self explanatory.

This is only data for the yahara watershed that is used otherwise for testing. I think this is the right way to have done this relative to how the yahara data was done.

It includes:
toc.dat
4030.dat
4031.dat
4033.dat
4032.dat
restore.sql

restore.sql does not include table creation. These tables will need to be created in the liquibase job and the data loaded in [2_load_network.sh](https://github.com/ACWI-SSWD/nldi-db/blob/master/dbInit/2_load_network.sh) in addition to the [nhdplus_yahara.backup.gz](https://github.com/ACWI-SSWD/nldi-db/blob/master/dbInit/nhdplus_yahara.backup.gz)

The four tables here are described below. They can be joined on the charid column of the data tables and the 'row' column of the metadata table:
```
-- Table: charadata.acc_charadata

-- DROP TABLE charadata.acc_charadata;

CREATE TABLE charadata.acc_charadata
(
    seq integer,
    comid integer,
    charaid smallint,
    val numeric,
    nodatap smallint
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE charadata.acc_charadata
    OWNER to  nldi;
```

```
-- Table: charadata.cat_charadata

-- DROP TABLE charadata.cat_charadata;

CREATE TABLE charadata.cat_charadata
(
    seq integer,
    comid integer,
    charaid smallint,
    val numeric,
    nodatap smallint
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE charadata.cat_charadata
    OWNER to nldi;
```

```
-- Table: charadata.tot_charadata

-- DROP TABLE charadata.tot_charadata;

CREATE TABLE charadata.tot_charadata
(
    seq integer,
    comid integer,
    charaid smallint,
    val numeric,
    nodatap smallint
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE charadata.tot_charadata
    OWNER to nldi;
```

```
-- Table: charadata.charametadata

-- DROP TABLE charadata.charametadata;

CREATE TABLE charadata.charametadata
(
    "row" integer NOT NULL,
    "ID" text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    units text COLLATE pg_catalog."default",
    "datasetLabel" text COLLATE pg_catalog."default",
    "datasteURL" text COLLATE pg_catalog."default",
    "themeLabel" text COLLATE pg_catalog."default",
    "themeURL" text COLLATE pg_catalog."default",
    "watershedType" text COLLATE pg_catalog."default",
    CONSTRAINT charametadata_pkey PRIMARY KEY ("row")
)
WITH (
    OIDS = TRUE
)
TABLESPACE pg_default;

ALTER TABLE charadata.charametadata
    OWNER to nldi;
```

### CODE REVIEW

**Comment by mbucknell** [comment]
Should we be designating seq as the primary key for the acc_charadata, cata_charadata and tot_charadata tables?

**Comment by dblodgett-usgs** [comment]
I actually intended for that to be the case. Whatever it becomes, I will make it the primary key.

**Comment by ayan-usgs** [comment]
> "datasteURL" text COLLATE pg_catalog."default",

Spelling error in "datasteURL.

More generally, I would expect that to be some foreign key constraints to be defined between the `charametadata` table and `*_charadata` tables. Presumably, there must be some link between the characteristic data and the metadata.

**Comment by dblodgett-usgs** [comment]
Thanks.

The foreign key constraint would be that they can be joined on the charid column of the data tables and the 'row' column of the metadata table. I could add the foreign key constraint now or should we layer that on in the liquibase job?

Also, per Dave Steinich's comments in JIRA, I am planning on renaming things:
acc_charadata -> divergence_routed_characteristics
tot_charadata -> total_accumulated_characteristics
cat_charadata -> local_catchment_characteristics

For those tables' column names:
seq -> sequence
comid -> comid
charaid -> characteristic_id
val -> characteristic_value
nodatap -> percent_nodata
charametadata -> characteristic_metadata

For the metadata table, column names become:
row -> characteristic_id
ID -> characteristic_text_id
datasetLabel -> dataset_label
datasetUrl -> dataset_url
themeLabel -> theme_label
themUrl -> theme_label
watershedType -> characteristic_type

**Comment by dblodgett-usgs** [comment]
see #34 for the update to this PR.

**Pull request closed without merging**
